### PR TITLE
Use GNU grep if available, on macOS as well

### PR DESCRIPTION
**Pull request by kissge**
Hope zim teams also like this. Or if not, please feel free to just close this PR.

### CODE REVIEW

**Comment by ericbn** [comment]
Thanks for the contribution, @kissge!

**Comment by ericbn** [comment]
After trying it out I decided to revert the change, because it causes the grep alias to not be created in macOS if ggrep does not exist.

**Comment by kissge** [comment]
I see.

On my second thought, isn't this all we need?:

```
  if (( ${+commands[ggrep]} )); then
     alias grep='ggrep --color=auto'
  else
    alias grep='grep --color=auto'
  fi
```

**Comment by ericbn** [comment]
The goal of the module is to enable colors and add some extra handy aliases, not replace BSD tools by GNU ones. This can be done separately. E.g. in macOS with homebrew and the grep formula installed, you can add `PATH="/usr/local/opt/grep/libexec/gnubin:$PATH"` to your .zshrc file.

**Pull request merged**
